language: csharp
dist: trusty
mono: none
dotnet: 2.1.402
script:
  - dotnet test Antlr3.Test -f netcoreapp2.0 --filter TestCategory!=SkipOnCI
  - dotnet test Antlr4.Test.StringTemplate -f netcoreapp2.0
